[project]
name = "cmrl-passenger-data-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx[cli]>=0.28.1",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
